name: Run Python Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.6
    - name: Install virtualenv
      run: |
        pip install virtualenv  # Install virtualenv

    - name: Create virtual environment
      run: |
        python -m venv mlflow_venv  # Create a virtual environment
        source mlflow_venv/bin/activate  # Activate the virtual environment
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Serve Mlflow model for testing
      run: |
         MODEL_PATH="./model" # path of the model
         mlflow models serve -m $MODEL_PATH -p 5000 --env-manager=local &
         # Wait a bit for the server to start
         sleep 15
    - name: Test using dummy data
      run: |
        curl -X POST http://localhost:5000/invocations \
          -H "Content-Type: application/json" \
          --data '{
            "instances": [
              {
                "unit_number": 1,
                "time_in_cycles": 100,
                "op_setting_1": 0.1,
                "op_setting_2": 0.2,
                "op_setting_3": 0.3,
                "sensor_measurement_1": 0.0,
                "sensor_measurement_2": 0.8,
                "sensor_measurement_3": 0.0,
                "sensor_measurement_4": 0.0,
                "sensor_measurement_5": 0.0,
                "sensor_measurement_6": 0.0,
                "sensor_measurement_7": 0.0,
                "sensor_measurement_8": 0.0,
                "sensor_measurement_9": 0.0,
                "sensor_measurement_10": 0.0,
                "sensor_measurement_11": 0.0,
                "sensor_measurement_12": 0.0,
                "sensor_measurement_13": 0.6,
                "sensor_measurement_14": 0.0,
                "sensor_measurement_15": 0.0,
                "sensor_measurement_16": 0.3,
                "sensor_measurement_17": 0.0,
                "sensor_measurement_18": 0.0,
                "sensor_measurement_19": 0.0,
                "sensor_measurement_20": 0.0,
                "sensor_measurement_21": 0.0
              }
            ]
          }'

