name: Run Python Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install virtualenv
      run: |
        pip install virtualenv  # Install virtualenv

    - name: Create virtual environment
      run: |
        python -m venv mlflow_venv  # Create a virtual environment
        source mlflow_venv/bin/activate  # Activate the virtual environment
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Serve Mlflow model for testing
      run: |
         MODEL_PATH="./model" # path of the model
         mlflow models serve -m $MODEL_PATH -p 5000 --env-manager=local &
         # Wait a bit for the server to start
         sleep 15
         # Ping the endpoint 
         curl http://localhost:5000/invocations
