name: Serve MLflow Model

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ 'model/**' ]

jobs:
  serve-model:
    runs-on: ubuntu-latest
    container:
      image: python:3.8-slim
      ports:
        - 5000:5000
      options: --health-cmd "curl -f http://localhost:5000/ping || exit 1" --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install mlflow
        pip install wait-for-it

    - name: Start MLflow model server
      run: |
        echo "Starting MLflow model server..."
        mlflow models serve -m ./model -p 5000 -h 0.0.0.0 &
        wait-for-it localhost:5000 --timeout=60 --strict -- echo "MLflow server is up!"

    - name: Test model endpoint
      run: |
        curl -X POST -H "Content-Type:application/json; format=pandas-split" \
          --data '{"columns":["feature1","feature2"],"data":[[1.0, 2.0]]}' \
          http://localhost:5000/invocations
